### ISSUE TITLE
Не работает клавиатура и квадраты на современном телевизоре...

### ISSUE THREAD

**Issue by pbadun** [sdima1357/spectrum48_tv#1]
День добрый.
Подключил все кроме внешней флэшки.
1. Не работает клавиатура (использовал обычную так и беспроводную (сдвоенная: клавиатура+тач))
2. На современном телевизоре картинка испорченна, квадраты и сбита строчная развертка, но не целиком, а как-то блоками, как-раз на высоту квадратов...

**Comment by sdima1357** [comment]
1.Клавиатура с роутером внутри (комби) работать не будет.  Роутинг не поддерживается ST.
2. Добавьте делитель и ФНЧ. Амплитуда выхода больше чем по стандарту. (3.3V vs 1.0V)

**Comment by pbadun** [comment]
А можно поподробнее ? :)
1. я так-же брал обычную клавиатуру - не было эффекта. (лампочек на ней так-же не горело)...
2. можно схемку или пример этого делителя?

**Comment by sdima1357** [comment]
Некоторые клавиатуры только 5 вольт. Проверьте , что там есть.На плате есть
вход для 5 вольт.
Порядка 100 ом последовательно и ~0.5 нанофарад параллельно

**Comment by pbadun** [comment]
![IMG_20210106_201540](https://user-images.githubusercontent.com/6719861/103801250-85fc8980-505e-11eb-9097-a8bbb065cfaf.jpg)

Получил вот такую картинку.

Замерял напряжение на USB порте, 1В при старте и где-то 0.8 при работе...

**Comment by pbadun** [comment]
На плате стоит защитный диод (или что-то на него очень похожее). Возможно вы за питали клавиатуру отдельно? Скажем через USB хаб с блокам питания?

**Comment by sdima1357** [comment]
Нет там никаких диодов
https://github.com/WeActTC/MiniF4-STM32F4x1/blob/master/HDK/MiniF4x1Cx_V13%20SchDoc.pdf

**Comment by pbadun** [comment]
![tt](https://user-images.githubusercontent.com/6719861/103818692-10061b80-507a-11eb-81e1-c5d27e15a813.jpg)

Вот, отмечено синим.
До него - 5 вольт есть, после - 1 вольт.
Что-то мне кажется у меня более новая ревизия или серийный брак, т.к. две платы и один и тот-же эффект...

**Comment by pbadun** [comment]
https://github.com/WeActTC/MiniF4-STM32F4x1/blob/master/HDK/MiniF4x1Cx_V30%20SchDoc.pdf

Вот... по ходу такая версия у меня :(

**Comment by sdima1357** [comment]
Учитесь читать схемы, это чип U2:
https://github.com/WeActTC/MiniF4-STM32F4x1/blob/master/Datasheet/AP7343D-33FS4-7B.PDF
Он никак не связан с USB (Кроме общей земли).

**Comment by pbadun** [comment]
Этот чип рядом.

Начиная с ревизии v 2.2 в схему добавлен диод для защиты от перепадов при питании по USB
https://github.com/WeActTC/MiniF4-STM32F4x1/tree/master/HDK#v22

**Comment by sdima1357** [comment]
Попробуйте закоротить этот диод.Они похоже только в режиме device проверяли.

**Comment by sdima1357** [comment]
PS  - У меня другая версия -  без диода. С диодом не видел. Sorry

**Comment by sdima1357** [comment]
Собсвенно с диодом и не будет работать в режиме host.  Закоротите.
